### ISSUE TITLE
[BUG] Agents: Issue with the "Get User Information" in Report Portal tool for Agents

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#512]
**Given** a user begins the process of creating an agent
**And** as part of the agent setup, selects Report Portal as the tool of choice
**And** configures it as necessary, Upon saving the tool settings and initiating data retrieval related to the user
**When** the user triggers the execution of the "Get User Information" command
**Then** the agent responds with an error message.
Here is a error 
Traceback (most recent call last):   File "/tmp/tmposu4p47y/lib/python3.10/site-packages/langchain_core/tools/base.py", line 555, in run     response = context.run(self._run, *tool_args, **tool_kwargs)   File "/tmp/tmposu4p47y/lib/python3.10/site-packages/alita_tools/base/tool.py", line 24, in _run     return self.api_wrapper.run(self.name, *args, **kwargs)   File "/tmp/tmposu4p47y/lib/python3.10/site-packages/alita_tools/report_portal/api_wrapper.py", line 204, in run     return tool["ref"](*args, **kwargs)   File "/tmp/tmposu4p47y/lib/python3.10/site-packages/alita_tools/report_portal/api_wrapper.py", line 139, in get_user_information     return self.client.get_user_information(username)   File "/tmp/tmposu4p47y/lib/python3.10/site-packages/alita_tools/report_portal/report_portal_client.py", line 66, in get_user_information     response.raise_for_status()   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status     raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error:  for url:
https://reportportal.epam.com/api/v1/user/liana_gevorgyan

Note: talked with developer, he said seems API was changed, so need to look on it.
Checked on [eYe env ](https://eye.projectalita.ai/)

**Comment by plageat** [comment]
Usser info API is deprecated in version 5.xx.
See also
https://github.com/ProjectAlita/application-tools/pull/84

**Comment by liana-gif** [comment]
Verified
